version: "3.1"

networks:
  default:
  nginx_main:
    external: true

secrets:
  django_secret_key:
    file: ./secrets/django_secret_key.txt
  django_admin_user:
    file: ./secrets/django_admin_user.txt
  django_admin_email:
    file: ./secrets/django_admin_email.txt
  django_admin_pass:
    file: ./secrets/django_admin_pass.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  certbot_email:
    file: ./secrets/certbot_email.txt
  key.pem:
    file: ./secrets/key.pem

services:

    postgres:
        image: "postgres:latest"
        environment:
          POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
          POSTGRES_DB: "clickgestion"
        secrets:
          - postgres_password
        restart: unless-stopped
        networks:
          default:

    django:
        build: ./django_container/
        volumes:
          - ./django_container/app:/app
        depends_on:
          - postgres
        command: uwsgi ./clickgestion/uwsgi.ini --procname-master uwsgim
        secrets:
          - postgres_password
          - django_secret_key
          - django_admin_user
          - django_admin_email
          - django_admin_pass
        environment:
          DJANGO_SETTINGS_MODULE: clickgestion.settings.development
        restart: unless-stopped
        networks:
          default:

    nginx:
        build: ./nginx_container/
        volumes:
          - ./django_container/app/clickgestion/static/:/app/static/
          - ./nginx_container/logs:/etc/nginx/logs/
        depends_on:
          - django
        environment:
          CERTBOT_EMAIL: /run/secrets/certbot_email
        secrets:
         - source: certbot_email
        restart: unless-stopped
        networks:
          default:
          nginx_main:
            ipv4_address: 172.16.0.7
