# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-19 20:14
from __future__ import unicode_literals

import clickgestion.concepts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepts', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_required', models.BooleanField(default=False, verbose_name='Date Required')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('per_adult', models.BooleanField(default=False, verbose_name='Book Per Adult')),
                ('per_child', models.BooleanField(default=False, verbose_name='Book Per Child')),
                ('per_night', models.BooleanField(default=False, verbose_name='Book Per Night')),
                ('per_senior', models.BooleanField(default=False, verbose_name='Book Per Senior')),
                ('per_unit', models.BooleanField(default=False, verbose_name='Book Per Unit')),
                ('price_per_adult', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='Price Per Adult')),
                ('price_per_child', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='Price Per Child')),
                ('price_per_senior', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='Price Per Senior')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='Price Per Unit')),
                ('variable_price', models.BooleanField(default=False, verbose_name='Variable Price')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Tour/Show',
                'verbose_name_plural': 'Tours/Shows',
            },
        ),
        migrations.CreateModel(
            name='ShowCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Tour/Show Company',
                'verbose_name_plural': 'Tour/Show Companies',
            },
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('baseconcept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concepts.BaseConcept')),
                ('adults', models.SmallIntegerField(default=2, verbose_name='Adults')),
                ('children', models.SmallIntegerField(default=0, verbose_name='Children')),
                ('date_required', models.BooleanField(default=False, verbose_name='Date Required')),
                ('per_adult', models.BooleanField(default=False, verbose_name='Book Per Adult')),
                ('per_child', models.BooleanField(default=False, verbose_name='Book Per Child')),
                ('per_night', models.BooleanField(default=False, verbose_name='Book Per Night')),
                ('per_senior', models.BooleanField(default=False, verbose_name='Book Per Senior')),
                ('per_unit', models.BooleanField(default=False, verbose_name='Book Per Unit')),
                ('price_per_adult', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price Per Adult')),
                ('price_per_child', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price Per Child')),
                ('price_per_senior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price Per Senior')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price Per Unit')),
                ('seniors', models.SmallIntegerField(default=0, verbose_name='Seniors')),
                ('units', models.SmallIntegerField(default=1, verbose_name='Units')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket_sales.Show', verbose_name='Tour/Show')),
            ],
            options={
                'verbose_name': 'Ticket Sale',
                'verbose_name_plural': 'Ticket Sales',
            },
            bases=('concepts.baseconcept',),
        ),
        migrations.CreateModel(
            name='TicketSaleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=32, null=True, verbose_name='Department')),
                ('apt_number_required', models.BooleanField(default=False, verbose_name='Apt Number Required')),
                ('apt_number_visible', models.BooleanField(default=True, verbose_name='Apt Number Visible')),
                ('client_address_required', models.BooleanField(default=False, verbose_name='Address Required')),
                ('client_address_visible', models.BooleanField(default=True, verbose_name='Address Visible')),
                ('client_email_required', models.BooleanField(default=False, verbose_name='Email Required')),
                ('client_email_visible', models.BooleanField(default=True, verbose_name='Email Visible')),
                ('client_first_name_required', models.BooleanField(default=False, verbose_name='First Name Required')),
                ('client_first_name_visible', models.BooleanField(default=True, verbose_name='First Name Visible')),
                ('client_id_required', models.BooleanField(default=False, verbose_name='Passport/ID Required')),
                ('client_id_visible', models.BooleanField(default=True, verbose_name='Passport/ID Visible')),
                ('client_last_name_required', models.BooleanField(default=False, verbose_name='Last Name Required')),
                ('client_last_name_visible', models.BooleanField(default=True, verbose_name='Last Name Visible')),
                ('client_phone_number_required', models.BooleanField(default=False, verbose_name='Phone Required')),
                ('client_phone_number_visible', models.BooleanField(default=True, verbose_name='Phone Visible')),
                ('client_signature_required', models.BooleanField(default=False, verbose_name='Client Signature Required')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('employee_signature_required', models.BooleanField(default=False, verbose_name='Employee Signature Required')),
                ('notes_required', models.BooleanField(default=False, verbose_name='Notes Required')),
                ('notes_visible', models.BooleanField(default=True, verbose_name='Notes Visible')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='VAT Percent')),
                ('permission_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Permission Group')),
            ],
            options={
                'verbose_name': 'Ticket Sale Settings',
                'verbose_name_plural': 'Ticket Sale Settings',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='ticket_sales.ShowCompany', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='show',
            name='currency',
            field=models.ForeignKey(default=clickgestion.concepts.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='concepts.Currency', verbose_name='Currency'),
        ),
    ]
