# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 20:45
from __future__ import unicode_literals

import clickgestion.transactions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_desk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Apt Number')),
                ('code', models.CharField(default=clickgestion.transactions.models.get_new_transaction_code, editable=False, max_length=32, unique=True, verbose_name='Code')),
                ('client_address', models.TextField(blank=True, max_length=512, null=True, verbose_name='Address')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('client_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('client_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Passport/ID')),
                ('client_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('client_phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Close Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('notes', models.TextField(blank=True, max_length=512, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cashclose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cash_desk.CashClose', verbose_name='Cash Desk Close')),
                ('employee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
