# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_desk', '0002_auto_20190411_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashclose',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
