# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFloatDeposit',
            fields=[
                ('baseconcept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.BaseConcept')),
            ],
            options={
                'verbose_name': 'Cash Float Deposit',
                'verbose_name_plural': 'Cash Float Deposits',
            },
            bases=('transactions.baseconcept',),
        ),
        migrations.CreateModel(
            name='CashFloatDepositSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percent', models.FloatField(default=0, verbose_name='VAT Percent')),
                ('apt_number', models.BooleanField(default=False, verbose_name='Apt Number Required')),
                ('client_address', models.BooleanField(default=False, verbose_name='Address Required')),
                ('client_email', models.BooleanField(default=False, verbose_name='Email Required')),
                ('client_first_name', models.BooleanField(default=False, verbose_name='First Name Required')),
                ('client_id', models.BooleanField(default=False, verbose_name='Passport/ID Required')),
                ('client_last_name', models.BooleanField(default=False, verbose_name='Last Name Required')),
                ('client_phone_number', models.BooleanField(default=False, verbose_name='Phone Required')),
            ],
            options={
                'verbose_name': 'Cash Float Deposit Settings',
                'verbose_name_plural': 'Cash Float Deposit Settings',
            },
        ),
        migrations.CreateModel(
            name='CashFloatWithdrawal',
            fields=[
                ('baseconcept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.BaseConcept')),
            ],
            options={
                'verbose_name': 'Cash Float Withdrawal',
                'verbose_name_plural': 'Cash Float Withdrawals',
            },
            bases=('transactions.baseconcept',),
        ),
        migrations.CreateModel(
            name='CashFloatWithdrawalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percent', models.FloatField(default=0, verbose_name='VAT Percent')),
                ('apt_number', models.BooleanField(default=False, verbose_name='Apt Number Required')),
                ('client_address', models.BooleanField(default=False, verbose_name='Address Required')),
                ('client_email', models.BooleanField(default=False, verbose_name='Email Required')),
                ('client_first_name', models.BooleanField(default=False, verbose_name='First Name Required')),
                ('client_id', models.BooleanField(default=False, verbose_name='Passport/ID Required')),
                ('client_last_name', models.BooleanField(default=False, verbose_name='Last Name Required')),
                ('client_phone_number', models.BooleanField(default=False, verbose_name='Phone Required')),
            ],
            options={
                'verbose_name': 'Cash Float Withdrawal Settings',
                'verbose_name_plural': 'Cash Float Withdrawal Settings',
            },
        ),
    ]
