# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_float', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='apt_number',
            new_name='apt_number_required',
        ),
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='client_address',
            new_name='client_address_required',
        ),
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='client_email',
            new_name='client_email_required',
        ),
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='client_first_name',
            new_name='client_first_name_required',
        ),
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='client_id',
            new_name='client_id_required',
        ),
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='client_last_name',
            new_name='client_last_name_required',
        ),
        migrations.RenameField(
            model_name='cashfloatdepositsettings',
            old_name='client_phone_number',
            new_name='client_phone_number_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='apt_number',
            new_name='apt_number_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='client_address',
            new_name='client_address_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='client_email',
            new_name='client_email_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='client_first_name',
            new_name='client_first_name_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='client_id',
            new_name='client_id_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='client_last_name',
            new_name='client_last_name_required',
        ),
        migrations.RenameField(
            model_name='cashfloatwithdrawalsettings',
            old_name='client_phone_number',
            new_name='client_phone_number_required',
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='apt_number_visible',
            field=models.BooleanField(default=False, verbose_name='Apt Number Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='client_address_visible',
            field=models.BooleanField(default=False, verbose_name='Address Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='client_email_visible',
            field=models.BooleanField(default=False, verbose_name='Email Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='client_first_name_visible',
            field=models.BooleanField(default=False, verbose_name='First Name Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='client_id_visible',
            field=models.BooleanField(default=False, verbose_name='Passport/ID Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='client_last_name_visible',
            field=models.BooleanField(default=False, verbose_name='Last Name Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='client_phone_number_visible',
            field=models.BooleanField(default=False, verbose_name='Phone Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='notes_required',
            field=models.BooleanField(default=False, verbose_name='Notes Required'),
        ),
        migrations.AddField(
            model_name='cashfloatdepositsettings',
            name='notes_visible',
            field=models.BooleanField(default=False, verbose_name='Notes Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='apt_number_visible',
            field=models.BooleanField(default=False, verbose_name='Apt Number Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='client_address_visible',
            field=models.BooleanField(default=False, verbose_name='Address Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='client_email_visible',
            field=models.BooleanField(default=False, verbose_name='Email Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='client_first_name_visible',
            field=models.BooleanField(default=False, verbose_name='First Name Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='client_id_visible',
            field=models.BooleanField(default=False, verbose_name='Passport/ID Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='client_last_name_visible',
            field=models.BooleanField(default=False, verbose_name='Last Name Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='client_phone_number_visible',
            field=models.BooleanField(default=False, verbose_name='Phone Visible'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='notes_required',
            field=models.BooleanField(default=False, verbose_name='Notes Required'),
        ),
        migrations.AddField(
            model_name='cashfloatwithdrawalsettings',
            name='notes_visible',
            field=models.BooleanField(default=False, verbose_name='Notes Visible'),
        ),
    ]
