# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_float', '0002_auto_20190225_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='apt_number_visible',
            field=models.BooleanField(default=True, verbose_name='Apt Number Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='client_address_visible',
            field=models.BooleanField(default=True, verbose_name='Address Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='client_email_visible',
            field=models.BooleanField(default=True, verbose_name='Email Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='client_first_name_visible',
            field=models.BooleanField(default=True, verbose_name='First Name Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='client_id_visible',
            field=models.BooleanField(default=True, verbose_name='Passport/ID Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='client_last_name_visible',
            field=models.BooleanField(default=True, verbose_name='Last Name Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='client_phone_number_visible',
            field=models.BooleanField(default=True, verbose_name='Phone Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatdepositsettings',
            name='notes_visible',
            field=models.BooleanField(default=True, verbose_name='Notes Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='apt_number_visible',
            field=models.BooleanField(default=True, verbose_name='Apt Number Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='client_address_visible',
            field=models.BooleanField(default=True, verbose_name='Address Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='client_email_visible',
            field=models.BooleanField(default=True, verbose_name='Email Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='client_first_name_visible',
            field=models.BooleanField(default=True, verbose_name='First Name Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='client_id_visible',
            field=models.BooleanField(default=True, verbose_name='Passport/ID Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='client_last_name_visible',
            field=models.BooleanField(default=True, verbose_name='Last Name Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='client_phone_number_visible',
            field=models.BooleanField(default=True, verbose_name='Phone Visible'),
        ),
        migrations.AlterField(
            model_name='cashfloatwithdrawalsettings',
            name='notes_visible',
            field=models.BooleanField(default=True, verbose_name='Notes Visible'),
        ),
    ]
